### ISSUE TITLE
App cannot be verified

### ISSUE THREAD

**Issue by Giszmo** [Airbitz/airbitz-android-gui#21]
At the time of writing [this article](https://walletscrutiny.com/posts/2019/11/airbitz/), we were unable to verify the apk on GooglePlay and we would hope to see this wallet - although obsoleted by its successor - to raise to our "verifiable" category soon with your cooperation.

**Comment by swansontec** [comment]
I read the article, and it did locate the correct commit in the correct repo. However, the build depends on assets and tools that are pretty out-of-date, and may not even be available anymore since Google has obsoleted 32-bit apps. It would be an interesting exercise to get this old code running again, but I don't expect it will be easy. Even back in the day when we were maintaining this code, we never put any effort into deterministic builds. Even if you could get it to build, verifying the APK might still be another big project.

I think you might have much more luck with the Edge app - not only is it maintained, but a vast majority of the code is in Javascript, which has much more deterministic builds. Plus, with yarn.lock, you know the exact version of every library we are using.

**Comment by Giszmo** [comment]
So this app remains not verifiable? Feel free to close this issue then. It's pretty scary but you probably hope people to migrate to edge anyway.
